//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasreddinsSecretListener.Companion.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NasreddinsSecretListener.Companion.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yellow|Auto-Connect zu &apos;Mein Gerät&apos;… ähnelt.
        /// </summary>
        public static string Status_AutoconnectToMyDevice {
            get {
                return ResourceManager.GetString("Status_AutoconnectToMyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue|Verbunden. Lausche auf gefundene Magneten… ähnelt.
        /// </summary>
        public static string Status_ConnectedAndListen {
            get {
                return ResourceManager.GetString("Status_ConnectedAndListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orange|Verbindung fehlgeschlagen. ähnelt.
        /// </summary>
        public static string Status_ConnectionFailed {
            get {
                return ResourceManager.GetString("Status_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orange|Auto-Connect fehlgeschlagen. Bitte näher ran und erneut versuchen. ähnelt.
        /// </summary>
        public static string Status_ConnectionFailedDuringAutoconnect {
            get {
                return ResourceManager.GetString("Status_ConnectionFailedDuringAutoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinde zu &apos;Mein Gerät&apos;… ähnelt.
        /// </summary>
        public static string Status_ConnectionToMyDevice {
            get {
                return ResourceManager.GetString("Status_ConnectionToMyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinde nach ähnelt.
        /// </summary>
        public static string Status_ConnectTo {
            get {
                return ResourceManager.GetString("Status_ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magenta|Kein Magnet ähnelt.
        /// </summary>
        public static string STATUS_DEVICE_00_NO_MAGNET {
            get {
                return ResourceManager.GetString("STATUS_DEVICE_00_NO_MAGNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yellow|Annäherung Magnet ähnelt.
        /// </summary>
        public static string STATUS_DEVICE_01_EARLY {
            get {
                return ResourceManager.GetString("STATUS_DEVICE_01_EARLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green|Magnet erkannt ähnelt.
        /// </summary>
        public static string STATUS_DEVICE_02_CONFIRMED {
            get {
                return ResourceManager.GetString("STATUS_DEVICE_02_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Status von Gerät ähnelt.
        /// </summary>
        public static string STATUS_DEVICE_XX_UNKNOWN {
            get {
                return ResourceManager.GetString("STATUS_DEVICE_XX_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orange:Kein &apos;Mein Gerät&apos; gespeichert. ähnelt.
        /// </summary>
        public static string Status_NoMyDeviceStored {
            get {
                return ResourceManager.GetString("Status_NoMyDeviceStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scannen… ähnelt.
        /// </summary>
        public static string Status_Scanning {
            get {
                return ResourceManager.GetString("Status_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan gestoppt. ähnelt.
        /// </summary>
        public static string Status_ScanStopped {
            get {
                return ResourceManager.GetString("Status_ScanStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Gerät wählen. ähnelt.
        /// </summary>
        public static string Status_SelectDevice {
            get {
                return ResourceManager.GetString("Status_SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  als *Mein Gerät* gespeichert&quot; ähnelt.
        /// </summary>
        public static string Status_StoredAsMyDevice {
            get {
                return ResourceManager.GetString("Status_StoredAsMyDevice", resourceCulture);
            }
        }
    }
}
